### ISSUE TITLE
Strings not available for translation

### ISSUE THREAD

**Issue by dikonov** [jdrescher2006/Laufhelden#106]
Here is a list of strings that are missing from the translation file:
- "Version:" (About screen)
- "Welcome to Laufhelden", XX "km", "Xh Xm Xs", "No earlier workouts" (Main screen)
- "Login", "User Name", "not logged in", "Email:", "Country:" (Strava setup page)

* Sport-tracker.com has no Russian version, but Strava has. Therefore, Russian speakers who did not spend years learning English/German are likely to choose Strava.

**Comment by dikonov** [comment]
I have already added extra translations:
"Russian male" for the voice (I plan to make corresponding sound files)
"Russian", "Version:" for the about page

**Comment by jdrescher2006** [comment]
Thanks for that informations. I will look into it!

**Comment by jdrescher2006** [comment]
Those strings should all be available in the translation file. If not please reopen this issue!
