### ISSUE TITLE
Is it possible to connect bike computer HRM

### ISSUE THREAD

**Issue by dikonov** [jdrescher2006/Laufhelden#108]
I have two wireless bike computers Sigma BC1909 with working heart rate monitors but cannot pair them with Laufhelden. Scanning does not show them. 

Is there any chance to support their protocol (and  wireless speed/cadence sensors of different bike computers)? They can use BTLe or NFC... 

Could you add some help on choosing compatible HRM monitors? 
It would be supercool to describe their integration with bike computers and smart watches too.

_* Sigma has some built-in model of HR threshold levels dependency on sex, age and weight. The user specifies his physical parameters (sex, age and weight) and the HR levels are calculated automatically. It might be possible to implement the same in the app._

**Comment by jdrescher2006** [comment]
BTLe devices are not supported in Laufhelden. Someone is working on a BTLe HR app, if this is ready, Laufhelden might support that.
The only two HR devices which will work with the app are:
- Polar Wearlink Bluetooth: https://support.polar.com/us-en/WearlinkBluetooth
- Zephyr HxM Bluetooth: https://www.zephyranywhere.com/resources/hxm

About the HR thresholds, it would be cool to have such a feature in Laufhelden. The only problem is, we need the data which HR thresholds should be set for a specific sex, age and weight.

**Comment by dikonov** [comment]
What about amazfit BIT watch? Will Laufhelden get its HR data?

**Comment by jdrescher2006** [comment]
Yes that works. The HR data is provided via the app Amazfish.

**Comment by jdrescher2006** [comment]
BLE is working now with version 1.1.3
