### ISSUE TITLE
Sportstracker Uploads

### ISSUE THREAD

**Issue by jdrescher2006** [jdrescher2006/Laufhelden#110]
The uploads to sports-tracker.com are not working. @niemisenjussi could you have a look into that?

**Comment by niemisenjussi** [comment]
Hi,

Actually uploads are working fine when upload is done from exercise detail -view. There has been [b71622ad63670e33b1ab49440e34441c5db21ee5](https://github.com/jdrescher2006/Laufhelden/commit/b71622ad63670e33b1ab49440e34441c5db21ee5#diff-786edfcde9c32e323d59f4a4cee0a1b4) -commit which deleted loading element from MainPage.

I restored this code and made a new pull-request.


Br. Jussi

**Comment by jdrescher2006** [comment]
Hi Jussi,
I am afraid that was me breaking sports tacker upload, sorry. Thanks for the fix!
