### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by ncartron** [jdrescher2006/Laufhelden#124]
Hi Jens,

I just finished French translation, and wanted to commit it, but don't have permissions.
How can I send it to you?

Cheers,
Nico

**Comment by jdrescher2006** [comment]
Hi Nico,

if you fork my repo, you can do a pull request. Then I can merge it into my code.

Best regards,
Jens

**Comment by ncartron** [comment]
Hi Jens,

just did it, thanks!

BR,
Nico

**Comment by jdrescher2006** [comment]
French should be included in 1.1.3 so I am closing this now.
Thanks for your good work and the christmas gift!

**Comment by ncartron** [comment]
You're welcome Jens, glad you received it in time! ;)
