### ISSUE TITLE
Can you add a Transifex page?

### ISSUE THREAD

**Issue by dashinfantry** [jdrescher2006/Laufhelden#140]
I can translate your app more convenient.

**Comment by dashinfantry** [comment]
I need Chinese .Thanks!✺◟(∗❛ัᴗ❛ั∗)◞✺

**Comment by dashinfantry** [comment]
I don't know how to create a ts file, thereforce a transifex page is necessary.Thanks!

**Comment by eson57** [comment]
You don't need to create ts file, you can just [download raw](https://github.com/jdrescher2006/Laufhelden/raw/master/translations/harbour-laufhelden.ts) from this repository an translate using Qt Linguist.

**Comment by dashinfantry** [comment]
It  is complex
