### ISSUE TITLE
error trying to install

### ISSUE THREAD

**Issue by rr-gh** [jdrescher2006/Laufhelden#157]
I get the following error message when I try to install the program via storeman:
... there is no ressource for "libQt5Bluetooth.so.5" available which is required for harbour-laufhelden-1.1.3.1.armv7hl...
My device runs Sailfish OS 3.1.0.11
Thanks for any  hint in advance.

**Comment by jdrescher2006** [comment]
Have you tried pkcon refresh in the terminal?

**Comment by rr-gh** [comment]
I just retired, now installation works fine. As I am running Sailfish OS 3.3.0.14 meanwhile it is hard to track back what the problem was. Thanks for the trigger to retry anyway :-)
