### ISSUE TITLE
Feature request: PayPal - Bitcoin Donation.

### ISSUE THREAD

**Issue by Caballlero** [jdrescher2006/Laufhelden#17]
I want to give a **Pizza-Hut** to this  nice project. 
Also a  compatibility with OSMScountServer is very needed.

**Comment by jdrescher2006** [comment]
Hi Caballlero, thanks for your donation request. I will add a paypal link on openrepos in next release.
OSMScountServer is a difficult thing, I already requested using it in the TMO thread: [https://talk.maemo.org/showpost.php?p=1528251&postcount=253](url)
