### ISSUE TITLE
Can't install on SFOS 2.1.1.26

### ISSUE THREAD

**Issue by Karry** [jdrescher2006/Laufhelden#3]
Hi. when I wanted to install this app via Warehouse, I got gpg error on geoservices package (from Jolla repo). Do you have idea how to solve it?
![screenshot_20170917_001](https://user-images.githubusercontent.com/309458/30519952-a8404932-9ba3-11e7-9f9d-228ff3ee450a.png)

**Comment by jdrescher2006** [comment]
I have no idea what that means. I tested the app on a Jolla 1 and OPX both can install without problems. Could you try to install Rena from openrepos? It uses the same packages as Laufhelden.

**Comment by Karry** [comment]
Hi. I have the same issue with Rena :-( Did you install it from warehouse? Or you install this package (`qt5-plugin-geoservices-osm`) from another source? It is always possible to ignore gpg signature from command line, but it is something that I don't want to do :-)

**Comment by jdrescher2006** [comment]
I can install Rena on both phones without problems. OPX is on 2.1.0.11 and Jolla is on 2.1.1.26.
I really don't know how to help you or what to do about the problem.
By the way, Laufhelden has 122 downloads now on openrepos. The other users don't seem to have your problem.

**Comment by wb1000000** [comment]
I also experienced an error trying to install it from the warehouse:

Nothing provides libQt5Bluetooth.so.5

I'm using a Jolla C with 2.1.1.26.

Do you know how to solve this? I would really like to try it out.

Best regards,

Jasper

**Comment by jdrescher2006** [comment]
That's really strange. Please try `pkcon refresh` in terminal.

**Comment by wb1000000** [comment]
That did the trick thanks!

Best regards,

Jasper

**Comment by Karry** [comment]
It helps me to :-) Thanks! I am closing this issue... You may add this command to pre-install script.

**Comment by Olf0** [comment]
Repository metadata from Jolla's RPM repositories not being properly updated is a common issue / pattern, thus IMO `pkcon refresh` should not be added to a specific application.
