### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by CaptainKhan** [jdrescher2006/Laufhelden#34]
Please see: https://together.jolla.com/question/175371/laufhelden-feature-request/

Propose name during submittal to SportsTracker  similar to file name save using format, yyyy-mm-dd_activity_Distance_time or something like it.

In track list view on long press in addition to remove add menue option send to sports tracker. Also please inlude Common Units: 1km = 0.6213712mi and 1km = 3280.84ft to calculate mi/hr, min/mi. 

Future, it would be nice if map tiles could be cashed, so when running in same area with crappy or no internet it would re-use the tiles.

**Comment by jdrescher2006** [comment]
The SportsTracker implementation was done by @niemisenjussi. He made some improvememts which will be included in the next release. We would have to ask him for further improvemements.

Switching between metric/imperial units is definitely on my ToDo list. Unfortunately the list is very long and this will be a lot of work. Let' see...

Map tiles are already beeing cached in the directory: /home/nemo/.cache/harbour-laufhelden/Laufhelden/QtLocation. I have nearly 5000 files in that folder. Please have a look if you have files there on your phone.

**Comment by jdrescher2006** [comment]
All problems described here should be fixed with new version v1.1.0
