### ISSUE TITLE
Translation strings not working

### ISSUE THREAD

**Issue by eson57** [jdrescher2006/Laufhelden#43]
I found three strings that do not translate in app. Line 183-192 in .ts file.

![screen_20180106_002](https://user-images.githubusercontent.com/2996154/34637284-06cec472-f2b3-11e7-8156-8c33eaf755f7.png)

**Comment by jdrescher2006** [comment]
I will take a look into that. Thanks a lot for reporting errors! I wish more users would do that.

**Comment by eson57** [comment]
Well, reporting bugs and errors is the least I can do. I know most users don't care.

**Comment by jdrescher2006** [comment]
This is really strange. I cannot reproduce that error. I switched my Jolla 1 to swedish language and restarted phone. Then did a fresh install of Laufhelden 0.9.8 from openrepos.
The three strings are OK, see screenshot.
Do you really have the 0.9.8 official version from openrepos?
![skarmbild_20180106_001](https://user-images.githubusercontent.com/12234756/34643197-62c5d2b2-f320-11e7-9feb-e67710684002.png)

**Comment by eson57** [comment]
Yes, I do. I upgraded this morning and the about page says 0.9.8-9. I even replaced the sv.qm file to make sure there was nothing wrong with my update.
It is strange, because now I reinstalled Laufhelden and what do you know... now it works. 
Sorry I made you work for nothing, I just didn't think of reinstalling.

**Comment by eson57** [comment]
I still don't understand but I found how to reproduce. The error occurs when i replace the released packet language file to the latest updated file. The one I pushed this morning. I can't remember I've had any problem doing this before. This is the way I always test my translations.

**Comment by jdrescher2006** [comment]
OK I pulled your file from this morning and recompiled the app. I get no errors while processing the language files. Everything is OK and the strings are OK when I switch to swedish.
I don't know, I will keep an eye on this.

**Comment by eson57** [comment]
Ok, I think I'll have to uninstall and clean up for a fresh install and new tests. There must be something wrong with my system. I'll be back tomorrow.

**Comment by eson57** [comment]
There actually was something fishy with my config. After clean reinstall the translations is working as they should. I will check the walking/running issue during the day. Several dog walks will be done.
Sorry to have bothered you with this s**t.

Btw... You do know you don't have to change your phone language to test an app language? This should do the trick...
`LANG=sv harbour-laufhelden`
