### ISSUE TITLE
Walking exercise is saved as running

### ISSUE THREAD

**Issue by eson57** [jdrescher2006/Laufhelden#44]
When I start new workout as walking, it is always saved as running.

**Comment by jdrescher2006** [comment]
Ok, I will check it out!

**Comment by jdrescher2006** [comment]
I tested on my Jolla 1 and OPX. I can not reproduce that error. Please make sure you have the official version from openrepos.
If you still have this problem, please describe exactly how to reproduce it.

**Comment by eson57** [comment]
The problem is still there, despite clean reinstallation and removing old track files.

- I just start the app with launcher. 
- Choose "Start new workout" from pulley menu. 
- Choose walking workout. 
- Hit "Let's go" and then "Start", as soon as GPS accuracy is good enough.

Here's start view...
![screen_20180107_005](https://user-images.githubusercontent.com/2996154/34648997-022e72e8-f3a6-11e7-81c5-c59724189096.png)

Here's end result...
![screen_20180107_003](https://user-images.githubusercontent.com/2996154/34649006-2f6f3850-f3a6-11e7-9e89-8528f709c317.png)
![screen_20180107_001](https://user-images.githubusercontent.com/2996154/34649013-3baf9fce-f3a6-11e7-9a61-ba37c103b2c2.png)
![screen_20180107_004](https://user-images.githubusercontent.com/2996154/34649015-4734e3fe-f3a6-11e7-81f9-de4b5a9f22db.png)

**Comment by eson57** [comment]
The above was manual saving. Auto saving was saved as walking.

**Comment by eson57** [comment]
This is fun. The app must be self healing. On fourth workout record, after clean reinstall, it suddenly start to save walking correctly. :)
Another thing is that metadata in gpx file says walking even in previous files saved as running.

**Comment by jdrescher2006** [comment]
Hi eson57. I am really busy with the map bug on long workouts #45 . After that I will return to this one.

**Comment by eson57** [comment]
No problem, take your time. I'm watching.

**Comment by jdrescher2006** [comment]
OK, I found one bug regarding this issue. If a workout was edited from the main (first) page, it would always show running in the edit dialog.
Let's see if I can find more bugs...

**Comment by eson57** [comment]
Great! One to go then. I found that workout seem to be saved (manually) randomly as walking/running. My fourth record was correctly saved as walking, then back to running on fifth record.

**Comment by jdrescher2006** [comment]
I got it now. The bug is on the pre record page where you can select the workout. If you don't change the workout type on this page (because the right workout is already selected from the workout before), the workout will always be saved as running. So only when you change the workout type in the combobox the new value will be used for the recording.

**Comment by jdrescher2006** [comment]
I already fixed it. Have to do a few more tests. If everything goes well, next release will be at start of next weak.

**Comment by eson57** [comment]
👍 Thanks!

**Comment by jdrescher2006** [comment]
Release v0.9.9-1 with bug fixes it out. Please test and report if there are still problems!

**Comment by eson57** [comment]
Yes, seem to work like expected. Good job!  👍
