### ISSUE TITLE
Laufhelden failed on long ride

### ISSUE THREAD

**Issue by piggz** [jdrescher2006/Laufhelden#45]
Went for a long (4+ hours) ride using Laufhelden.

When I finished and went to safe the ride, I found that Laufhelden had crashed and I had a blank cover window.

When opening again, laufhelden told me I had an activity in progress and offered to restore it.  I chose yes, but then laufhelden hung, and lipstick gave the 'app has stopped responding' option.  I chose to wait a few times, but it never started up.

Perhaps the ride was too long and took too much memory?  Possible memory leak?

**Comment by jdrescher2006** [comment]
Do you still have the autosave file? Can you send it to me?

**Comment by piggz** [comment]
Yes and yes .... what is its location?

**Comment by pfbach** [comment]
Had the same problem yesterday. Went on a 2-3 hours cross country skiing tour, it crashed when I tried to save it. Unfortunately, I don't think my autosave file survived.

**Comment by jdrescher2006** [comment]
I had the same problem yesterday while a long run of 27km. After 20km the app crashed. Autosave could not be restored.
Seems like I messed it up somehow. Will start debugging asap.

**Comment by jdrescher2006** [comment]
So there are at least two bugs. I found and fixed the one preventing to load the autosave. It has to do with the new map plugin. The other bug may be based on the same problem.

**Comment by rinigus** [comment]
I'll be checking whether it's caused by mapbox gl plugin at https://github.com/rinigus/mapbox-gl-qml/issues/28. Linking the issues for now

**Comment by jdrescher2006** [comment]
So this should be solved with release v0.9.9-1. Please test and report if you still have problems!
