### ISSUE TITLE
Spanish language did not come with the version 0.9.2-3

### ISSUE THREAD

**Issue by Caballlero** [jdrescher2006/Laufhelden#5]
After install -v 0.9.2-3 i can not get spanish.

**Comment by jdrescher2006** [comment]
Ok that's strange. I have to find out how to test this. Do you know if the emulator can be configured to other languages?

**Comment by Caballlero** [comment]
I know that  this strange. it is not emulator. I will do some test , I let you know later my test...

**Comment by jdrescher2006** [comment]
OK, I will also try it out. Set my phone to spanish language.

**Comment by jdrescher2006** [comment]
I found a bug in the spanish language file. I already fixed it, next release should have spanish language!

**Comment by Caballlero** [comment]
Thank you.
