### ISSUE TITLE
Can't be installed to Sailfish X 2.1.4.14 (EAP)

### ISSUE THREAD

**Issue by Nrde** [jdrescher2006/Laufhelden#63]
I'm trying to install Laufhelden from storeman, but even after enabling Rinigus' repos (by installing OSM scout server) Laufhelden can't be installed, it just keeps "installing..."
If it matters, I can't manually install Mapbox GL native bindings either.

**Comment by jdrescher2006** [comment]
That's strange, as far as I know it should work on Sailfish X. Have you tried pkcon refresh on the terminal?

**Comment by Nrde** [comment]
Yes, doesn't seem to help. But I'm now doing a full install with maps and everything of OSM scout server, so I'll get back to you if it made any difference.

**Comment by jdrescher2006** [comment]
Mapbox GL native bindings is a dependency for Laufhelden, you need to install this first. To get more error message output you could install the app manually.
To do this just download the RPM file with the browser. Then go into the terminal on the phone and type pkcon install-local ~/Downloads/xxx.rpm

**Comment by Nrde** [comment]
I could install it from command line, but storeman was just "installing". Maybe some issue with the dependencies that got resolved meanwhile?

**Comment by jdrescher2006** [comment]
I have no idea what the problem was. Maybe it could have something to do with the new packet system in the new Sailfish version.
I hope the app works correctly now.

**Comment by Nrde** [comment]
2018-03-12 11:21 GMT+01:00 Jens Drescher <notifications@github.com>:

> I have no idea what the problem was. Maybe it could have something to do
> with the new packet system in the new Sailfish version.
> I hope the app works correctly now.
>

​I haven't fully tested it yet, but one issue I found was that
sports-tracker "test sign in"​ button doesn't seemingly do anything. I.e.,
it tries to connect "Testing sign in" but it does nothing after that.
Eventually the text goes away I think (or if I go back and then come back
to sports-tracker page), but there's no indication if the test was
successful or not. Also the "test sign in" button is too narrow for the
text. (Finnish translation)

**Comment by jdrescher2006** [comment]
Could you please open a new issue for the sports tracker bug?

**Comment by Nrde** [comment]
Sure, I'll do it right away.
