### ISSUE TITLE
Sport-tracker test sign in does not work or doesn't report success or failure

### ISSUE THREAD

**Issue by Nrde** [jdrescher2006/Laufhelden#64]
After filling sports-tracker username and password, clicking "test sign in" button shows text "testing sign in", text doesn't disappear unless user navigates to the previous page, no other indication what is happening never appears.
expected output: A message or other notification if the test was successful or reason for failure.

**Comment by jdrescher2006** [comment]
There is a problem in the login function. I get a parse error in line `var loginresponse = JSON.parse(xmlhttp.responseText);` that is in the file SportsTracker.js.
That means that the sports tracker function of the app is broken in general.

**Comment by jdrescher2006** [comment]
@niemisenjussi: could you take a look into this? Maybe sports tracker has changed the login procedure.

**Comment by niemisenjussi** [comment]
Yes of course, I will make a new PR when I have resolved this issue.

**Comment by niemisenjussi** [comment]
This issue is now solved and [pull/67](https://github.com/jdrescher2006/Laufhelden/pull/67 ) is merged to master branch. So, this fix will be included in the next release.

**Comment by jdrescher2006** [comment]
@niemisenjussi: I noticed an other small thing. When the user wants to upload a workout to sports tracker, the description field is empty. You could use the name of the workout from the GPX file for that field. That would be more convenient for the user because he wouldn't have to enter the name twice.

**Comment by jdrescher2006** [comment]
All problems described here should be solved with the new version v1.1.0
