### ISSUE TITLE
mainpage.qml header row is missing correct left and right margins

### ISSUE THREAD

**Issue by Nrde** [jdrescher2006/Laufhelden#65]
Especially the left side with distance icon looks to be too close to the screen border. I think it's missing  Theme.horizontalPageMargin This is visible on sailfish X at least.
I can try to provide a fix if I manage to compile it myself...

**Comment by jdrescher2006** [comment]
Yes your right, good point. I will fix this in the next update.

**Comment by jdrescher2006** [comment]
The bug is fixed with version v1.1.0.
