### ISSUE TITLE
Feature Request: Do not ask for save with name.

### ISSUE THREAD

**Issue by CaptainKhan** [jdrescher2006/Laufhelden#9]
After stopping run give option to automatically save, simple assemble name by activity selected when starting workout, date and miles of exercise.

**Comment by jdrescher2006** [comment]
Oh, that's a really good idea.
I think there will be an option under settings to choose "Autosave workout". And then the workout name will be as `Running - 29.09.2017 - 10.6km`.
Question is if we really need the date. It makes the name relatively long and we already have the date on the overview page.

What do you think?

**Comment by CaptainKhan** [comment]
Yes as long as the system can handle it (maxstring length depending on folder) and it will properly display in the app.

A slightly different date format 2017-09-29 would also allow sort by name.

I think it looks great and would make the track files themselves easier to handle.

**Comment by jdrescher2006** [comment]
But these are two different things. We have the name which is stored within the GPX files. Then we have the filename of the GPX file.
The overview page gives the name from within the GPX files. Sorting on that page goes by date which is a separate field and has nothing to do with the name.

Do you want the name and the filename equal?

**Comment by CaptainKhan** [comment]
My thought is that if the display and file name is the same it would be easy to pase the data later on and say summarize miles by year by activity since all that data is already in the name. Also when importing files its easier to group amd sort if you know what the file may contain.

**Comment by jdrescher2006** [comment]
Ok that makes sense. I will put that into the next release. I am still struggeling with certain problems on the record page, so next release will last some time.

**Comment by jdrescher2006** [comment]
HI CaptainKhan, can we agree that this issue is fixed with 0.9.4-5 on openrepos?
