### ISSUE TITLE
STRAVA bug: username is null

### ISSUE THREAD

**Issue by jdrescher2006** [jdrescher2006/Laufhelden#92]
Hi @piggz,
I noticed a problem on the strava settings page. It seems that my username is null: `\"athlete\":{\"id\":30838888,\"username\":null`. That leads to the line `page.username = athlete["username"];` crashing. Maybe we can show the firstname and lastname instead of the username?

**Comment by piggz** [comment]
I wonder if it is related to how you logon to strava, do you use email or facebook?

**Comment by jdrescher2006** [comment]
Login via email, I don't have a facebook account.

**Comment by piggz** [comment]
i login via email too, so its not that!

**Comment by jdrescher2006** [comment]
Yes but maybe they took your username from a previous facebook login and saved it to your strava account. Anyway, we could work with an if statement at that place. If the username is null, use firstname and lastname instead.

**Comment by piggz** [comment]
sure

**Comment by jdrescher2006** [comment]
OK, I'm doing that right now.

**Comment by jdrescher2006** [comment]
I have pushed the menu entry "My Strava Activities" on the main page above "Start new workout". I hope that is OK for you.

**Comment by piggz** [comment]
yeah, i was thinking a few days ago it would be better moved
