### ISSUE TITLE
STRAVA bug: My Strava Activities not working

### ISSUE THREAD

**Issue by jdrescher2006** [jdrescher2006/Laufhelden#94]
@piggz: The page MyStravaActivities.qml is completely empty.  There seem to be no response. Maybe some API problems?
`[D] O2ReplyServer::O2ReplyServer:19 - O2ReplyServer: Starting
[D] O0BaseAuth::linked:33 - O0BaseAuth::linked: Yes
[D] :187 - Ready state changed: 2   200 OK
[D] :187 - Ready state changed: 3  [] 200 OK
[D] :187 - Ready state changed: 4  [] 200 OK
[D] :189 - Get Response: []`

**Comment by piggz** [comment]
working for me atm, and i uploaded activities last night even....i'll take a look.

does this mean you are now a strava user? :)

**Comment by jdrescher2006** [comment]
Yeah I am a strava user now. So far it's quite nice although I am a little bit annoyed by all their premium advertisements :-(

**Comment by piggz** [comment]
As it returned 200 ok, and you don't have any activities yet, maybe it is correct

**Comment by jdrescher2006** [comment]
I have 7 workouts online, all runnings. By the way, they are all marked as private.

**Comment by piggz** [comment]
i wonder if its an api 'feature' where they dont share private workouts with 3r party apps

**Comment by jdrescher2006** [comment]
That could be an explanation. So we can't do anything -> close this bug.

**Comment by piggz** [comment]
actually, reopen it, we can request view_private scope in the oauth request

**Comment by piggz** [comment]
https://developers.strava.com/docs/authentication/
