### ISSUE TITLE
STRAVA bug, cannot access private activities

### ISSUE THREAD

**Issue by piggz** [jdrescher2006/Laufhelden#96]
the strava oauth flow needs to request access to private rides for this, should we enable it?

**Comment by jdrescher2006** [comment]
What does that mean? Does the user need to accept it?

**Comment by piggz** [comment]
Change
https://github.com/jdrescher2006/Laufhelden/blob/master/qml/pages/StravaSettingsPage.qml#L56
to 
view_private,write

**Comment by jdrescher2006** [comment]
It works now with `scope: "view_private,write".` Although I had to relogin. Maybe we should somehow tell the users they need to do a relogin to activate this.

**Comment by piggz** [comment]
yeah, i anticipated having to rellgon.  perhaps just something in tbe release notes will.do?
